name: scvi_base
channels:
    - conda-forge
    - pytorch
dependencies:        
- pandas==0.24.2
- numpy==1.16.2
- scikit-learn==0.20.3
- matplotlib==3.0.3
- pip  = 19.0.3
- sympy = 1.4  
- torchvision-cpu = 0.2.2 
- pytorch-cpu = 1.0.1
- pip
- pip :
    jupyter-client = 5.2.3   
    jupyter-core  = 4.4.0    